services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    GAYA\Hcaptcha\:
        resource: '../Classes/*'

    GAYA\Hcaptcha\Service\ConfigurationService:
        public: true

